#!/usr/bin/env bash
# ============================================================
# teo-infra — generate nanomq/nanomq_pwd.conf from .env.
#
# NanoMQ has no env templating, so its account passwords cannot be read from the
# process environment the way api and nexus read theirs. Rather than commit the
# passwords in plaintext, this RENDERS the pwd file at bring-up time from the
# same MQTT_* values in .env that the app clients (talosot api/nexus) and the SPA
# already dial with. One source of truth, and nothing secret in git: the
# generated file is gitignored, only the .example is committed.
#
# Run automatically by boot.sh. Safe to run by hand:
#
#   ./gen-nanomq-pwd.sh
#
# Reads six vars, all REQUIRED — the broker rejects a blank password and all
# three roles are load-bearing (see nanomq/nanomq_acl.conf):
#
#   MQTT_USER        / MQTT_PASSWORD          service account (app api, nexus)
#   MQTT_NODE_USER   / MQTT_NODE_PASSWORD     device firmware
#   MQTT_VIEWER_USER / MQTT_VIEWER_PASSWORD   browsers (subscribe-only)
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env}"
OUT="${OUT:-$SCRIPT_DIR/nanomq/nanomq_pwd.conf}"

log() { printf '[gen-nanomq-pwd] %s\n' "$*"; }
die() { printf '[gen-nanomq-pwd] FATAL: %s\n' "$*" >&2; exit 1; }

[[ -f "$ENV_FILE" ]] || die "$ENV_FILE not found — run ./svc-build-env.sh first"

# Read ONE key from the compose .env. Takes the LAST assignment (compose is
# last-wins), strips a single surrounding quote pair, and un-doubles '$$' -> '$'
# so the value matches exactly what compose interpolates into the app clients and
# the SPA — the broker password MUST equal what the clients dial with.
read_env() { # <KEY> -> echoes raw value, or returns 1 if the key is absent
  local key="$1" line val
  line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n1)" || true
  [[ -n "$line" ]] || return 1
  val="${line#*=}"
  if [[ ${#val} -ge 2 ]]; then
    case "$val" in
      \"*\") val="${val:1:${#val}-2}" ;;
      \'*\') val="${val:1:${#val}-2}" ;;
    esac
  fi
  val="${val//\$\$/\$}"
  printf '%s' "$val"
}

require() { # <KEY> -> echoes value or dies (empty / placeholder both fail)
  local key="$1" val
  val="$(read_env "$key")" || die "$key is not set in $ENV_FILE"
  [[ -n "$val" ]] || die "$key is empty in $ENV_FILE"
  case "$val" in replace*) die "$key still holds a placeholder in $ENV_FILE" ;; esac
  printf '%s' "$val"
}

svc_user="$(require MQTT_USER)"
svc_pass="$(require MQTT_PASSWORD)"
node_user="$(require MQTT_NODE_USER)"
node_pass="$(require MQTT_NODE_PASSWORD)"
viewer_user="$(require MQTT_VIEWER_USER)"
viewer_pass="$(require MQTT_VIEWER_PASSWORD)"

# 0600 before any content lands. The pwd file is a secret; the broker mounts it
# read-only, so nothing needs it group/world readable.
umask 077
cat > "$OUT" <<EOF
# GENERATED by gen-nanomq-pwd.sh from .env — DO NOT EDIT, DO NOT COMMIT.
# Regenerated on every bring-up from the MQTT_*_USER / MQTT_*_PASSWORD values in
# .env. NanoMQ password file: HOCON "username: password" pairs, included by
# nanomq.conf -> auth.password. Roles/ACL: nanomq_acl.conf.
#
#   service (app api, nexus) — MQTT_USER        / MQTT_PASSWORD
#   node    (devices)        — MQTT_NODE_USER   / MQTT_NODE_PASSWORD
#   viewer  (browsers)       — MQTT_VIEWER_USER / MQTT_VIEWER_PASSWORD
${svc_user}: ${svc_pass}
${node_user}: ${node_pass}
${viewer_user}: ${viewer_pass}
EOF

log "wrote $OUT (accounts: ${svc_user}, ${node_user}, ${viewer_user})"
